[package]
name = "ds210finalproject"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
petgraph = "0.6"

[dev-dependencies]
tempfile = "3.3"
assert_cmd = "2.0"
